#!/usr/bin/python

import copy
import getopt
import sys
import os
import transsys
import transsys.optim 
import random
import pdb


transsys_name = None
parameters = None
model = None
replicate = None
rndseed = 1
rewiring_operations = 24

optlist, args = getopt.getopt(sys.argv[1:], 'n:w:r:s:h')

for opt, par in optlist :
  if opt == '-h' :
    print '-n: <Transsys program name>: Transsys program name'
    print '-w: <Number of rewirings>: Number of rewirings'
    print '-r: <Number of rewired topologies>: Number of rewired topologies'
    print '-s: <Random seed>: Random seed number'
    print '-h: print this help and exit'
    sys.exit()
  elif opt == '-n' :
    transsys_name = par
  elif opt == '-w' :
    rewirings = int(par)
  elif opt == '-r' :
    replicate = int(par)
  elif opt == '-s' :
    rndseed = int(par)
  else :
    raise StandardError, 'unhandled option "%s"' % opt

if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdout


