#!/usr/bin/env python

import sys
import getopt

import transsys


class RootCell(object) :
  """Represent a generic root cell.
"""

  def __init__(self, rootProgram, cellLengthFactor, initialLength) :
    # FIXME: check rootProgram for suitability
    self.state = transsys.TranssysInstance(rootProgram)
    self.cellLengthFactor = cellLengthFactor
    self.state.set_factor_concentration(self.cellLengthFactor, initialLength)


  def getLength(self) :
    return self.state.get_factor_concentration(self.cellLengthFactor)


  def update(self) :
    s = self.state.time_series(2)
    self.state = s[-1]


  def applyTreatment(self, treatmentFactor, treatmentConcentration) :
    self.state.set_factor_concentration(treatmentFactor, treatmentConcentration)


class RootEpidermisCell(RootCell) :
  """Represent a root epidermis cell.
"""


  def __init__(self, rootProgram, cellLengthFactor, initialLength) :
    super(RootEpidermisCell).__init__(rootProgram, cellLengthFactor, initialLength)


class RootEpidermisColumn(object) :
  """Represent a column of root epidermis cells.

@ivar rootProgram the transsys program
@ivar cellLengthFactor the factor in the transsys program that represents length
@ivar initialLength the initial length of epidermis cells, as they are emitted from the meristem
@ivar growthTrigger the factor in the transsys program that triggers emission of cells from the meristem
@ivar growthThreshold the concentration of the growthTrigger factor at which a new cell is emitted
"""

  def __init__(self, rootProgram, cellLengthFactor, initialLength, growthTrigger, growthThreshold) :
    self.rootProgram = rootProgram
    self.initialLength = initialLength
    self.growthTrigger = growthTrigger
    self.growthThreshold = growthThreshold
    self.cellList = []
    self.meristem = transsys.TransysInstance(self.rootProgram)


  def update(self) :
    for rootCell in self.cellList :
      rootCell.update()


  def applyTreatment(self, treatmentFactor, treatmentConcentration) :
    for rootCell in self.cellList :
      rootCell.applyTreatment(treatmentFactor, treatmentConcentration)
    

  def addCell(self) :
    """Add a cell to the tip of the column,
simulating the meristem emitting a new epidermis cell for this column.
"""
    self.cellList = [RootEpidermisCell(self.rootProgram, self.cellLengthFactor, self.initialLength)] + self.cellList


  def grow(self) :
    if self.meristem.getFactorConcentration(self.growthTrigger) >= self.growthThreshold :
      self.addCell()
      # FIXME: possibly set the concentration of growth_trigger to some lower value


globalTreatmentConcentration = 1.0
treatmentFactorList = []
initialLength = 5.0
nCells = None

def usage() :
  print 'usage:'
  print 'options:'
  print '-t <treatment list>: specify treatments (whitespace separated list)'
  print '-n <number>: specify number of cells to generate'
  print '-l <number>: specify initial length of juvenile root cell'
  print '-h: print this help and exit'


options, args = getopt.getopt(sys.argv[1:], 'n:t:h')
for opt, par in options :
  if opt == '-h' :
    usage()
    sys.exit()
  elif opt == '-t' :
    treatmentFactorList = par.split()
  elif opt == '-n' :
    nCells = int(par)
  else :
    raise StandardError, 'unhandled option "%s"' % opt
if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout
if nCells is None :
  raise StandardError, 'number of cells not specified'
parser = transsys.TranssysProgramParser(infile)
rootProgram = parser.parse()
rootCell = RootCell(rootProgram, initialLength)
for treatmentFactor in treatmentFactorList :
  rootCell.applyTreatment(treatmentFactor, globalTreatmentConcentration)
outfile.write('cellNo cellLength\n')
for t in xrange(nCells) :
  outfile.write('%d, %1.17e\n' % (t, rootCell.getLength()))
  rootCell.nextState()
