#!/usr/bin/env python

import sys
import getopt
import copy

import transsys


class RootCell(object) :
  """Represent a generic root cell.
"""

  def __init__(self, rootProgram, cellLengthFactor, initialLength) :
    try :
      self.state = transsys.TranssysInstance(rootProgram)
    except :
      print 'Error no transsys program provided'
    self.cellLengthFactor = cellLengthFactor
    self.state.set_factor_concentration(self.cellLengthFactor, initialLength)


  def getLength(self, factorName) :
    return self.state.get_factor_concentration(factorName)


  def update(self) :
    s = self.state.time_series(2)
    self.state = s[-1]


  def applyTreatment(self, treatmentFactor, treatmentConcentration) :
    self.state.set_factor_concentration(treatmentFactor, treatmentConcentration)


class RootEpidermisCell(RootCell) :
  """Represent a root epidermis cell.
"""


  def __init__(self, rootProgram, cellLengthFactor, initialLength) :
    super(RootEpidermisCell, self).__init__(rootProgram, cellLengthFactor, initialLength)


class RootEpidermisColumn(object) :
  """Represent a column of root epidermis cells.

@ivar rootProgram the transsys program
@ivar cellLengthFactor the factor in the transsys program that represents length
@ivar initialLength the initial length of epidermis cells, as they are emitted from the meristem
@ivar growthTrigger the factor in the transsys program that triggers emission of cells from the meristem
@ivar growthThreshold the concentration of the growthTrigger factor at which a new cell is emitted
"""

  def __init__(self, rootProgram, cellLengthFactor, initialLength, growthTrigger, growthThreshold) :
    self.rootProgram = rootProgram
    self.initialLength = initialLength
    self.cellLengthFactor = cellLengthFactor
    self.growthTrigger = growthTrigger
    self.growthThreshold = growthThreshold
    self.cellList = []


  def update(self) :
    for rootCell in self.cellList :
      rootCell.update()


  def applyTreatment(self, treatmentFactor, treatmentConcentration) :
    """ Apply treatment to cell column
@param treatmentFactor: name of treatment
@type treatmentFactor: C{String}
@param treatmentConcentration: concentration
@type treatmentConcentration: C{Int}
"""
    self.cellList.reverse()
    cellMeristem = self.cellList[0]
    cellMeristem.applyTreatment(treatmentFactor, treatmentConcentration) 
    c = cellMeristem.state.time_series(len(self.cellList))

    for i, rootCell in zip(c, self.cellList) :
      rootCell.state = i
    self.cellList.reverse()


  def addCell(self) :
    """Add a cell to the tip of the column,
simulating the meristem emitting a new epidermis cell for this column.
"""
    self.cellList = self.cellList + [RootEpidermisCell(self.rootProgram, self.cellLengthFactor, self.initialLength)]
    self.update()


  def grow(self) :
    """Simulating cell growth.
Cell will grow until a concentration reaches a threshold
"""

    self.addCell()
    cf = self.cellList[0]
    while cf.state.get_factor_concentration(self.growthTrigger) <= self.growthThreshold :
      self.addCell()
      cf = self.cellList[0]


globalTreatmentConcentration = 1.0
treatmentFactorList = []
initialLength = 5.0
celllLengthFactor = None
growthTrigger = None
growthThreshold = 0.0
nCells = 50
typeAnalysis = 'single'


def usage() :
  print 'usage:'
  print 'options:'
  print '-t <treatment list>: specify treatments (whitespace separated list)'
  print '-n <number>: specify number of cells to generate'
  print '-l <number>: specify initial length of juvenile root cell'
  print '-f <factor>: specify initial length factor of juvenile root cell'
  print '-x <factor>: specify growth trigger factor'
  print '-m <number>: specify growth threshold'
  print '-i <number>: type 1) multiple, 2) single'
  print '-h: print this help and exit'


options, args = getopt.getopt(sys.argv[1:], 'n:t:l:f:x:m:i:h')
for opt, par in options :
  if opt == '-h' :
    usage()
    sys.exit()
  elif opt == '-t' :
    treatmentFactorList = par.split()
  elif opt == '-n' :
    nCells = int(par)
  elif opt == '-l' :
    initialLength = int(par)
  elif opt == '-f' :
    cellLengthFactor = par
  elif opt == '-x' :
    growthTrigger = par
  elif opt == '-m' :
    growthThreshold = int(par)
  elif opt == '-i' :
    typeAnalysis = par
  else :
    raise StandardError, 'unhandled option "%s"' % opt
if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout
if nCells is None :
  raise StandardError, 'number of cells not specified'
rootProgram = transsys.TranssysProgramParser(infile).parse()


if typeAnalysis == 'single' :
  rootCell = RootCell(rootProgram, cellLengthFactor, initialLength)
  if len(treatmentFactorList) > 0 :
    for treatmentFactor in treatmentFactorList :
      rootCell.applyTreatment(treatmentFactor, globalTreatmentConcentration)
  outfile.write('cellNo cellLength\n')
  for t in xrange(nCells) :
    outfile.write('%d, %1.17e\n' % (t, rootCell.getLength(cellLengthFactor)))
    rootCell.update()

else :
  rootCell = RootEpidermisColumn(rootProgram, cellLengthFactor, initialLength, growthTrigger, growthThreshold)
  rootCell.grow()
  if len(treatmentFactorList) > 0 :
    for treatmentFactor in treatmentFactorList :
      rootCell.applyTreatment(treatmentFactor, globalTreatmentConcentration)

  outfile.write('cellNo cellLength\n')
  for t, v in enumerate(reversed(rootCell.cellList)) :
    outfile.write('%d, %1.17e\n' % (t, v.getLength(cellLengthFactor)))

