#!/usr/bin/python

import getopt
import sys
import os
import transsys
import transsys.optim 
from math import sqrt
import trsysmodis
import random

def write_result(f, optResult) :
 f.write('// objective: %g\n' % optResult.objectiveOptimum.fitness)
 f.write('%s\n' %  str(optResult.optimised_transsys_program))
 f.flush()



num_restarts = None
equilibration_length = None
optimiserfile = None
f_distance = None
verbose = 0
transformerfile = None
logfile = None
finalparam = None
logratio_offset = None
logratio_mode = False
rndseed = 0

optlist, args = getopt.getopt(sys.argv[1:], 'l:o:s:R:e:n:c:g:T:u:v:L:lvh')

for opt, par in optlist :
  if opt == '-h' :
    print '-l: logratio mode'
    print '-o <offset>: specify logratio offset'
    print '-s <int>: Random seed'
    print '-R  <int>: Random restarts'
    print '-e  <int>: Equilibration length'
    print '-n  <str>: Prefix name of target network'
    print '-c  <str>: Prefix name of candidate network'
    print '-g  <str>: Optimiser spec file name'
    print '-T  <str>: specify transformer specification file to parse'
    print '-u  <str>: 1: sum_squares, 2: correlation, 3: euclidean'
    print '-V  <int>: Verbose'
    print '-L  <str>: Logfile'
    print '-h: print this help and exit'
    sys.exit()
  elif opt == '-l' :
    logratio_mode = True
  elif opt == '-o' :
    logratio_offset = float(par)
  elif opt == '-s' :
    rndseed = int(par)
  elif opt == '-R' :
    num_restarts = int(par)
  elif opt == '-e' :
    equilibration_length = int(par)
  elif opt == '-n' :
    target_name = par
  elif opt == '-c' :
    candidate_name = par
  elif opt == '-g' :
    optimiserfile = par
  elif opt == '-T' :
    transformerfile = par
  elif opt == '-u' :
    f_distance = par
  elif opt == '-v' :
    verbose = int(par)
  elif opt == '-L' :
    result_file = par
  else :
    raise StandardError, 'unhandled option "%s"' % opt


if len(args) > 0 :   
  logfile = open(args[0], 'w')
if len(args) > 1 :   
  finalparam = open(args[1], 'w')

logo = file('%s_%s.txt'%(candidate_name, result_file),'w')

g = open(optimiserfile, 'r')
optimiser = transsys.optim.parse_optimiser(g)
g.close


if transformerfile is not None :
  g = open(transformerfile, 'r')
  optimiser.transformer = transsys.optim.parse_parameter_transformer(g)
g.close()

optimiser.verbose = verbose
rng = random.Random(rndseed)
optimiser.rng = rng

logo.write('restart\tfitness\n')
index = 0

x = open('%s_expr.txt'%target_name, 'r')
p = open('%s_pheno.txt'%target_name, 'r')
f = open('%s_feature.txt'%target_name, 'r')
expression_set = trsysmodis.ExpressionSet()
expression_set.read(x, p, f)
expression_set.shift_data()


objective_function = trsysmodis.KnockoutObjective(expression_set, equilibration_length)

if f_distance == 'sum_squares' :
  objective_function.distance_function = trsysmodis.distance_sum_squares
elif f_distance == 'correlation' :
  objective_function.distance_function = trsysmodis.distance_correl
elif f_distance == 'euclidean' :
  objective_function.distance_function = trsysmodis.distance_euclidean
else :
  raise StandardError, 'unknown distance %d' % f_distance

if logratio_mode :
  objective_function.distance_measu = expression_set.logratio_divergence
  expression_set.expression_data.logratio_offset = logratio_offset
else :
  objective_function.distance_measu = expression_set.divergence


optimiser.randomInitRange = 1.0
model = open('%s.tra'%(candidate_name),'r')

transsys_program = transsys.TranssysProgramParser(model).parse()

for restart_index in xrange(num_restarts) :
  print 'Using %s.tra'%(candidate_name)
  opt_result = optimiser.optimise(transsys_program, objective_function)
  logo.write('%d\t%f\n' % (restart_index, opt_result.objectiveOptimum.fitness))
  sys.stderr.write('%s\n' % str(objective_function(opt_result.optimised_transsys_program)))
  if finalparam is not None :
    write_result(finalparam, opt_result)
  if logfile is not None :
    opt_result.write_log(logfile, 'tp_index')

