#!/usr/bin/env python

import sys
import getopt
import transsys
import trsysmodis


def usage() :
  print 'usage:'
  print 'options:'
  print '-h: print this help and exit'


options, args = getopt.getopt(sys.argv[1:], 'h')
for opt, par in options :
  if opt == '-h' :
    usage()
    sys.exit()
  else :
    raise StandardError, 'unhandled option "%s"' % opt
if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout
p = trsysmodis.EmpiricalObjectiveFunctionParser(infile)
s = p.parse_objectivespec()
#outfile.write('%s\n' % str(s))
