#!/usr/bin/python

import copy
import getopt
import sys
import os
import transsys
import trsysmodis

optlist, args = getopt.getopt(sys.argv[1:], 't:h')

for opt, par in optlist :
  if opt == '-h' :
    print 'Usage: transsysspeccheck [options] spec_filename'
    print '-t: <Dummy>: Dummy parameter'
    print '-h: print this help and exit'
    sys.exit()
  if opt == '-n' :
    dummy = par
  else :
    raise StandardError, 'unhandled option "%s"' % opt

if len(args) > 0 :
  specfile = open(args[0], 'r')
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout

o = trsysmodis.SimGenexObjectiveFunctionParser(specfile)
objective_function = o.parse_objectivespec()
s = objective_function.__str__()
outfile.write('%s\n' % s)
