#!/usr/bin/python

import StringIO
import getopt
import sys
import os
import transsys
import transsys.optim 
from math import sqrt
import makemodel
import random


#./modelopt -r 2 -e 1000 -n 2 -m 'model_transsys' exp_data.txt pheno_data.txt grad.txt outfile.txt


def get_expr_data() :
  e = StringIO.StringIO()
  e.write('wt')
  for gene in gene_list :
     e.write('\t%s'%gene.name)
  e.write('\n')
  for factor in factor_list :
    e.write('%s'%factor.name)
    for array in range(len(gene_list)+1) :
      e.write('\t%d.2'%0.00)
    e.write('\n')
  e.seek(0)
  return e


def get_pheno_data() :
  p = StringIO.StringIO()
  list = 'MeJA'
  p.write('mutant\tgene\ttreatment')
  p.write('\n')
  p.write('wt\twildtype\tnone\t%s'%list)
  p.write('\n')
  for gene in gene_list :
    p.write('a%s\tknockout\t%s\t%s'%(gene.name,gene.name,list))
    p.write('\n')
  p.seek(0)
  return p


def get_feature_data() :
  f = StringIO.StringIO()
  f.write('\n')
  for factor in factor_list :
    f.write('%s'%factor.name)
    f.write('\n')
  f.seek(0)
  return f


num_restarts = None
equilibration_length = None
nu_m = None
model_ame = None
target_expr_data = None
target_pheno_data = None
target_feature_data = None
f_distance = None
rndseed = None
sigma = None

optlist, args = getopt.getopt(sys.argv[1:], 'r:x:p:f:e:s:lvh')

for opt, par in optlist :
  if opt == '-h' :
    print '-r <int>: specify random seed'
    print '-x <str>: specify gene expression profile file name'
    print '-p <str>: specify pheno data file name'
    print '-f <str>: specify feature data file name'
    print '-e <int>: Equilibration length'
    print '-s <int>: Sigma'
    print '-h: print this help and exit'
    sys.exit()
  elif opt == '-r' :
    rndseed = int(par)
  elif opt == '-e' :
    equilibration_length = int(par)
  elif opt == '-x' :
    target_expr_data = par
  elif opt == '-p' :
    target_pheno_data = par
  elif opt == '-s' :
    sigma = float(par)
  elif opt == '-f' :
    target_feature_data = par
  else :
    raise StandardError, 'unhandled option "%s"' % opt

rng = random.Random(rndseed)

if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
outfile_basename = args[1]


transsys_program = transsys.TranssysProgramParser(infile).parse()
factor_list = transsys_program.factor_list
gene_list = transsys_program.gene_list
e = get_expr_data()
p = get_pheno_data()
f = get_feature_data()

expression_set = makemodel.ExpressionSet()
expression_set.read(e, p, f)
objective_function = makemodel.KnockoutObjective(expression_set, equilibration_length)

if f_distance == 1 :
  objective_function.distance_function = makemodel.distance_sum_squares
elif f_distance == 2 :
  objective_function.distance_function = makemodel.distance_correl
else :
  objective_function.distance_function = makemodel.distance_euclidean

if rndseed is not None  :
  objective_function.write_noisy_simulated_set(transsys_program, outfile_basename, rng, sigma)
else :
  objective_function.write_simulated_set(transsys_program, outfile_basename)
