#!/usr/bin/python

import StringIO
import getopt
import sys
import os
import transsys
import trsysmodis
import random


spec = None
rndseed = 1
noise = 0.0
tracefile = None
tp_tracefile = None
biological_matrix_filename = None
selectedTpIndex = 1

optlist, args = getopt.getopt(sys.argv[1:], 's:o:N:b:t:lvh')
for opt, par in optlist :
  if opt == '-h' :
    print 'Usage: transsyswritesimsetOF [options] transsys_program expr_data_prefix track_file '
    print '-s <int>: Random seed'
    print '-N <int>: Noise'
    print '-o <str>: specify spec file'
    print '-t <num>: specify number of transsys program to process (default is first program in file)'
    print '-b <filename>: specify name for biological "raw" matrix'
    print '-h: print this help and exit'
    sys.exit()
  elif opt == '-o' :
    spec = par
  elif opt == '-s' :
    rndseed = int(par)
  elif opt == '-e' :
    equilibration_length = int(par)
  elif opt == '-N' :
    noise = float(par)
  elif opt == '-b' :
    biological_matrix_filename = par
  elif opt == '-t' :
    selectedTpIndex = int(par)
  else :
    raise StandardError, 'unhandled option "%s"' % opt

rng = random.Random(rndseed)

if len(args) > 0 :
  infile = open(args[0], 'r')
else :
  infile = sys.stdin
if len(args) > 1 :
  outfile = open(args[1], 'w')
else :
  outfile = sys.stdout
if len(args) > 2 :
  if args[2] != 'None' :
    tracefile = open(args[2], 'w')
if len(args) > 3 :
  if args[3] != 'None' :
    tp_tracefile = open(args[3], 'w')

specfile = open(spec, 'r')
o = trsysmodis.SimGenexObjectiveFunctionParser(specfile)
objective_function = o.parse_objectivespec()

tpParser = transsys.TranssysProgramParser(infile)
i = 0
while i < selectedTpIndex :
  transsys_program = tpParser.parse()
  i = i + 1
if transsys_program is None :
  raise StandardError, 'input does not contain %s programs' % selectedTpIndex
e = objective_function.get_simulated_set(transsys_program)

# FIXME: is this still in the API? doesn't look like it should be...
if noise > 0.0 :
  if rndseed is not None :
    #e.write_noisy_simulated_set(outfile, rng, noise)
    e.write_expression_data(outfile, rng, noise)
else :
  e.write_expression_data(outfile)
  if biological_matrix_filename is not None :
    f = open(biological_matrix_filename, 'w')
    e.annotation['biological_expression_set'].write_expression_data(f)
    f.close()
